

class VALUE_TYPE_CODE:
    TEXT = 'text'
    INT = 'int'
    FLOAT = 'float'
    IMAGE = 'image'


class FILTER_CODE:
    NO_FILTER = 'no filter'
    CATEGORY = 'category'


DEFAULT_FILTER_CODE = FILTER_CODE.NO_FILTER
DEFAULT_VALUE_TYPE_CODE = VALUE_TYPE_CODE.TEXT

CATALOG_NAME_MAX_LENGTH = 20
