

class VALUE_TYPE_CODE:
    TEXT = 'text'
    INT = 'int'
    FLOAT = 'float'
    IMAGE = 'image'


class FILTER_CODE:
    NO_FILTER = 'no filter'
    CATEGORY = 'category'


# Default values
DEFAULT_CODE_FILTER = FILTER_CODE.NO_FILTER
DEFAULT_CODE_VALUE_TYPE = VALUE_TYPE_CODE.TEXT
DEFAULT_COLUMN_NUMBER = 5
DEFAULT_ROW_NUMBER = 4

# Detail View
DETAIL_VIEW_SPACING = 5
DETAIL_VIEW_SPAN_HORIZONTAL = 150
DETAIL_VIEW_SPAN_VERTICAL = 100

# Color
COLOR_BLACK = (0, 0, 0)
COLOR_GREY_DARK = (40, 55, 71)
COLOR_GREY_LIGHT = (174, 182, 191)
COLOR_GREY_MEDIUM = (93, 109, 126)
COLOR_GREY_VERY_LIGHT = (214, 219, 223)
COLOR_WHITE = (255, 255, 255)

# Button
BUTTON_BORDER_WIDTH = 1
BUTTON_COLOR_BACKGROUND = COLOR_GREY_VERY_LIGHT
BUTTON_COLOR_BACKGROUND_HOVER = COLOR_GREY_LIGHT
BUTTON_COLOR_BACKGROUND_PRESSED = COLOR_GREY_DARK
BUTTON_COLOR_TEXT = COLOR_BLACK
BUTTON_COLOR_TEXT_HOVER = COLOR_BLACK
BUTTON_COLOR_TEXT_PRESSED = COLOR_WHITE
BUTTON_FONT_SIZE = 9
BUTTON_MARGIN = 2
BUTTON_PADDING = 3
BUTTON_RADIUS = (10, 7)


# Display Widget
DW_COLOR_DARK = COLOR_GREY_DARK
DW_COLOR_LIGHT = COLOR_GREY_MEDIUM
DW_MARGIN = 10
DW_PAINT_LINE_GAP = 5
DW_PAINT_WIDTH = 4
DW_RADIUS = 10.0
DW_SPACING = 16
DW_TITLE_FONT_SIZE = 11

# Other
CATALOG_NAME_MAX_LENGTH = 20
