# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catalog_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(742, 434)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sort_label = QtWidgets.QLabel(Form)
        self.sort_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sort_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sort_label.setObjectName("sort_label")
        self.horizontalLayout.addWidget(self.sort_label)
        self.sort_combo_box = QtWidgets.QComboBox(Form)
        self.sort_combo_box.setObjectName("sort_combo_box")
        self.horizontalLayout.addWidget(self.sort_combo_box)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.filter_area = QtWidgets.QScrollArea(self.splitter)
        self.filter_area.setWidgetResizable(True)
        self.filter_area.setObjectName("filter_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 358, 203))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.filter_area.setWidget(self.scrollAreaWidgetContents_2)
        self.article_area = QtWidgets.QScrollArea(self.splitter)
        self.article_area.setWidgetResizable(True)
        self.article_area.setObjectName("article_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 357, 203))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.article_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sort_label.setText(_translate("Form", "Sorting:"))
