# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catalog_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from UI.widget.button import Button
from UI.widget.combo_box import ComboBox


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(871, 434)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stack_widget = QtWidgets.QStackedWidget(Form)
        self.stack_widget.setObjectName("stack_widget")
        self.explore_stack = QtWidgets.QWidget()
        self.explore_stack.setObjectName("explore_stack")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.explore_stack)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.setting_button = Button(self.explore_stack)
        self.setting_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setting_button.setText("")
        self.setting_button.setObjectName("setting_button")
        self.horizontalLayout.addWidget(self.setting_button)
        self.add_button = Button(self.explore_stack)
        self.add_button.setText("")
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.sort_label = QtWidgets.QLabel(self.explore_stack)
        self.sort_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sort_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sort_label.setObjectName("sort_label")
        self.horizontalLayout.addWidget(self.sort_label)
        self.sort_combo_box = ComboBox(self.explore_stack)
        self.sort_combo_box.setObjectName("sort_combo_box")
        self.horizontalLayout.addWidget(self.sort_combo_box)
        self.sort_direction = Button(self.explore_stack)
        self.sort_direction.setEnabled(False)
        self.sort_direction.setText("")
        self.sort_direction.setCheckable(False)
        self.sort_direction.setChecked(False)
        self.sort_direction.setObjectName("sort_direction")
        self.horizontalLayout.addWidget(self.sort_direction)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.explore_stack)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.filter_area = QtWidgets.QScrollArea(self.splitter)
        self.filter_area.setWidgetResizable(True)
        self.filter_area.setObjectName("filter_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 413, 194))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.filter_area.setWidget(self.scrollAreaWidgetContents_2)
        self.article_area = QtWidgets.QScrollArea(self.splitter)
        self.article_area.setWidgetResizable(True)
        self.article_area.setObjectName("article_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 413, 194))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.article_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.splitter)
        self.stack_widget.addWidget(self.explore_stack)
        self.detail_stack = QtWidgets.QWidget()
        self.detail_stack.setObjectName("detail_stack")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.detail_stack)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stack_widget.addWidget(self.detail_stack)
        self.horizontalLayout_2.addWidget(self.stack_widget)

        self.retranslateUi(Form)
        self.stack_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sort_label.setText(_translate("Form", "Sorting:"))
