# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'component_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from UI.widget.check_box import CheckBox
from UI.widget.combo_box import ComboBox


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(383, 109)
        Form.setAutoFillBackground(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sorting_check_box = CheckBox(Form)
        self.sorting_check_box.setObjectName("sorting_check_box")
        self.horizontalLayout_2.addWidget(self.sorting_check_box)
        self.filter_combo_box = ComboBox(Form)
        self.filter_combo_box.setObjectName("filter_combo_box")
        self.horizontalLayout_2.addWidget(self.filter_combo_box)
        self.value_type_combo_box = ComboBox(Form)
        self.value_type_combo_box.setObjectName("value_type_combo_box")
        self.horizontalLayout_2.addWidget(self.value_type_combo_box)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.default_label = QtWidgets.QLabel(Form)
        self.default_label.setObjectName("default_label")
        self.horizontalLayout.addWidget(self.default_label)
        self.default_line_edit = QtWidgets.QLineEdit(Form)
        self.default_line_edit.setObjectName("default_line_edit")
        self.horizontalLayout.addWidget(self.default_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sorting_check_box.setText(_translate("Form", "Sortable"))
        self.default_label.setText(_translate("Form", "Default value:"))
